/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7p2_linsyposso;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 29164
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jppm_tree = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jtf_lineaComando = new javax.swing.JTextField();
        jB_enter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree_archivos = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_productos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_new = new javax.swing.JMenuItem();
        jmi_import = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem1.setText("Load File");
        jppm_tree.add(jMenuItem1);

        jMenuItem2.setText("Refresh Trees");
        jppm_tree.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtf_lineaComando.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jtf_lineaComando, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 50));

        jB_enter.setText("Enter");
        jB_enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_enterMouseClicked(evt);
            }
        });
        jPanel1.add(jB_enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 160, 40));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("CSVs");
        jTree_archivos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree_archivos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, 480));

        jTable_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Category", "Price", "Aisle", "Bin"
            }
        ));
        jScrollPane2.setViewportView(jTable_productos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 590, 480));

        jMenu1.setText("File");

        jmi_new.setText("New File");
        jmi_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_newActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_new);

        jmi_import.setText("Import File");
        jmi_import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_importActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_import);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Window");

        jMenu4.setText("Clear");

        jMenuItem3.setText("Clear Command Line");
        jMenu4.add(jMenuItem3);

        jMenuItem5.setText("Clear Table");
        jMenu4.add(jMenuItem5);

        jMenu2.add(jMenu4);

        jMenuItem4.setText("Refresh Tree");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_enterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_enterMouseClicked
        if (jtf_lineaComando.getText().contains("./load")) {
            cargardeArchivo();
            jtf_lineaComando.setText("");
        } else if (jtf_lineaComando.getText().contains("./create")) {
            try {
                crearArchivo();
                jtf_lineaComando.setText("");
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if (jtf_lineaComando.getText().contains("./clean")){
            limpiarTable();
            jtf_lineaComando.setText("");
        }
    }//GEN-LAST:event_jB_enterMouseClicked

    private void jmi_importActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_importActionPerformed
        cargardeArchivo();
    }//GEN-LAST:event_jmi_importActionPerformed

    private void jmi_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_newActionPerformed
        try {
            crearArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmi_newActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private void cargardeArchivo() {
        File archivo = null;
        FileReader fr = null;
        try {
            archivo = new File("./data.txt");
            leer = new Scanner(archivo);
            DefaultTableModel modelo = (DefaultTableModel) jTable_productos.getModel();
            modelo.setRowCount(0);
            while (leer.hasNext()) {
                String next = leer.nextLine();
                String[] tk = next.split(",");
                System.out.println(next);

                Object[] row = {tk[0], tk[1], tk[2], tk[3], tk[4], tk[5]};
                
                modelo.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        leer.close();
    }

    private void crearArchivo() throws IOException {
        DefaultTableModel modelo = (DefaultTableModel) jTable_productos.getModel();
        String acum = "";

        File archivo = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            String l = jtf_lineaComando.getText();
            String[] parse = l.split(" ");
            archivo = new File("./" + parse[1]);
            fw = new FileWriter(archivo, true);
            bw = new BufferedWriter(fw);
            for (int i = 0; i < modelo.getRowCount(); i++) {
                for (int j = 0; j < modelo.getColumnCount(); j++) {
                    if (modelo.getValueAt(i, j) != null) {
                        modelo.getValueAt(i, j);
                        acum += modelo.getValueAt(i, j) + ",";
                    }
                }
                bw.write(acum);
                acum = "";
            }
            bw.newLine();
            bw.flush();
        } catch (Exception e) {
        }
        bw.close();
        fw.close();
    }
    
    private void limpiarTable(){    
        DefaultTableModel model = (DefaultTableModel) jTable_productos.getModel();
        int f = jTable_productos.getRowCount();
        for (int i = 0; f > i; i++) {
            model.removeRow(0);
        }
        model.setRowCount(5);
    }
    
    private void 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_enter;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_productos;
    private javax.swing.JTree jTree_archivos;
    private javax.swing.JMenuItem jmi_import;
    private javax.swing.JMenuItem jmi_new;
    private javax.swing.JPopupMenu jppm_tree;
    private javax.swing.JTextField jtf_lineaComando;
    // End of variables declaration//GEN-END:variables
static Scanner leer = new Scanner(System.in);
    Producto pr = new Producto();
    int abc = 0;
}
